# Generated by Django 2.1.5 on 2019-01-26 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beverage', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pastas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pasta', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salad', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topping', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Price',
            new_name='Total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='Basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='orders.Basics'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Beverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beverage', to='orders.Beverages'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta', to='orders.Pastas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad', to='orders.Salads'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='orders.Subs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='orders.Toppings'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
