# Generated by Django 2.1.5 on 2019-01-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190126_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basics',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
