# Generated by Django 2.1.5 on 2019-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190126_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pastas',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salads',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
