# Generated by Django 2.1.5 on 2019-01-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190126_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='Size',
            field=models.CharField(default='small', max_length=64),
            preserve_default=False,
        ),
    ]
