# Generated by Django 2.1.5 on 2019-02-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_basics_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad_adding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adding', models.CharField(max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
