# Generated by Django 2.1.5 on 2019-03-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190219_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Basic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Beverage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Salad',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Sub',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Topping',
        ),
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
