# Generated by Django 2.1.5 on 2019-03-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190309_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.CharField(default='not', max_length=64),
        ),
    ]
