# Generated by Django 3.0.2 on 2020-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finished',
            field=models.CharField(default='pending', max_length=64),
        ),
    ]
